/**
 * security_audit — Security Audit Skill (gstack /cso port)
 *
 * Phase 4: Security Audit Skill
 *
 * Comprehensive security audit that:
 *   1. Scans for secrets in the codebase (API keys, tokens, passwords)
 *   2. Checks dependency vulnerabilities via npm audit
 *   3. Runs OWASP Top 10 analysis on code patterns
 *   4. Reviews MCP server security (tool permissions, data access)
 *   5. Generates structured security report with exploit scenarios
 *
 * gstack inspiration:
 *   /cso runs OWASP Top 10 + STRIDE threat modeling with
 *   zero-noise filtering (8/10 confidence gate). Each finding
 *   includes a concrete exploit scenario.
 *
 * @module skills/security_audit
 */

import path from "path";
import { fileURLToPath } from "url";
import { runSecurityScan } from "../src/security/scanner.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// ═══════════════════════════════════════════════════════════════════════════════
// Report Generator
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Generates a structured markdown security report from scan findings.
 *
 * @param {object} scanResult - Result from runSecurityScan()
 * @returns {string} Markdown report
 */
function generateReport(scanResult) {
  const { summary, findings } = scanResult;
  const now = new Date().toISOString().split("T")[0];

  let report = `# 🔒 Security Audit Report\n\n`;
  report += `**Date:** ${now}\n`;
  report += `**Findings:** ${summary.total} total (${summary.bySeverity.HIGH} HIGH, ${summary.bySeverity.MEDIUM} MEDIUM, ${summary.bySeverity.LOW} LOW)\n\n`;

  // Executive Summary
  report += `## Executive Summary\n\n`;
  report += `| Severity | Count |\n|----------|-------|\n`;
  report += `| 🔴 HIGH | ${summary.bySeverity.HIGH} |\n`;
  report += `| 🟡 MEDIUM | ${summary.bySeverity.MEDIUM} |\n`;
  report += `| 🟢 LOW | ${summary.bySeverity.LOW} |\n`;
  report += `| **Total** | **${summary.total}** |\n\n`;

  // By Category
  report += `### By Category\n\n`;
  for (const [cat, count] of Object.entries(summary.byCategory)) {
    report += `- **${cat}**: ${count}\n`;
  }
  report += "\n";

  // HIGH severity findings
  const highFindings = findings.filter((f) => f.severity === "HIGH");
  if (highFindings.length > 0) {
    report += `## 🔴 High Severity Findings\n\n`;
    for (const f of highFindings) {
      report += `### ${f.label}\n\n`;
      report += `- **File:** \`${f.file}:${f.line}\`\n`;
      report += `- **Match:** \`${f.match}\`\n`;
      report += `- **Confidence:** ${Math.round(f.confidence * 100)}%\n`;
      report += `- **Category:** ${f.category}\n\n`;

      // Generate exploit scenario
      report += `**Exploit Scenario:**\n`;
      report += `${generateExploitScenario(f)}\n\n`;

      // Fix recommendation
      if (f.fix) {
        report += `**Recommended Fix:** ${f.fix}\n\n`;
      }

      report += `---\n\n`;
    }
  }

  // MEDIUM severity findings
  const medFindings = findings.filter((f) => f.severity === "MEDIUM");
  if (medFindings.length > 0) {
    report += `## 🟡 Medium Severity Findings\n\n`;
    report += `| # | Issue | File | Line | Confidence |\n|---|-------|------|------|------------|\n`;
    medFindings.forEach((f, i) => {
      report += `| ${i + 1} | ${f.label} | \`${f.file}\` | ${f.line} | ${Math.round(f.confidence * 100)}% |\n`;
    });
    report += "\n";
  }

  // LOW severity findings
  const lowFindings = findings.filter((f) => f.severity === "LOW");
  if (lowFindings.length > 0) {
    report += `## 🟢 Low Severity Findings\n\n`;
    report += `| # | Issue | File | Line |\n|---|-------|------|------|\n`;
    lowFindings.forEach((f, i) => {
      report += `| ${i + 1} | ${f.label} | \`${f.file}\` | ${f.line} |\n`;
    });
    report += "\n";
  }

  // Recommendations
  report += `## Recommendations\n\n`;
  report += `1. **Fix HIGH severity issues immediately** — ${highFindings.length} finding(s) require immediate attention\n`;
  report += `2. **Address MEDIUM severity issues this sprint** — ${medFindings.length} finding(s) should be fixed\n`;
  report += `3. **Review LOW severity issues when convenient** — ${lowFindings.length} finding(s) to consider\n`;
  if (findings.some((f) => f.category === "dependencies")) {
    report += `4. **Run \`npm audit fix\`** to address dependency vulnerabilities\n`;
  }
  if (findings.some((f) => f.category === "mcp_security")) {
    report += `5. **Review MCP server configurations** — ensure no hardcoded secrets or dangerous commands\n`;
  }
  report += "\n";

  // Footer
  report += `---\n*Report generated by lv-zero Security Audit on ${now}*\n`;

  return report;
}

/**
 * Generates an exploit scenario for a finding.
 * @param {object} finding
 * @returns {string}
 */
function generateExploitScenario(finding) {
  const scenarios = {
    "API Key": "An attacker who gains access to this repository can use this API key to make requests on your behalf, potentially incurring costs or accessing sensitive data. If this is a cloud provider key, they could spin up resources or exfiltrate data.",
    "Stripe/API Key Format": "This appears to be a service-specific API key. An attacker could use it to access your account, make unauthorized transactions, or access customer data.",
    "GitHub Token": "With this GitHub token, an attacker could push code to your repositories, access private repositories, modify CI/CD pipelines, or exfiltrate source code.",
    "Slack Token": "This Slack token could allow an attacker to read all messages in your workspace, send messages as the bot user, access files, and potentially pivot to other connected services.",
    "AWS Access Key": "An attacker with this AWS access key could provision EC2 instances, access S3 buckets, modify IAM roles, or launch cryptomining operations — potentially costing thousands of dollars.",
    "JWT Token": "This JWT token could allow an attacker to impersonate a user or service. If not expired, it provides authenticated access to the associated API.",
    "Hardcoded Password": "This password is exposed in plaintext. An attacker could use it to access the associated service, database, or application. Passwords should never be stored in code.",
    "Database Password": "With this database password, an attacker could connect directly to your database, read/write all data, drop tables, or exfiltrate sensitive information.",
    "Database Connection String": "This connection string contains credentials. An attacker could connect to your database directly, bypassing any application-level security controls.",
    "URL with Credentials": "This URL contains embedded credentials. An attacker could use them to access the service. Credentials in URLs are also often logged by proxies and servers.",
    "Private Key": "This private key could allow an attacker to impersonate your service, decrypt communications, or sign malicious code. Rotate immediately if this was ever committed.",
    "Secret Env Var": "This environment variable contains a secret value. While .env files are typically gitignored, if this was committed at any point, the secret should be rotated.",
    "A03: Code Injection (eval/exec)": "An attacker who can control input to eval() or exec() can execute arbitrary code on your server. This could lead to complete server compromise, data exfiltration, or ransomware.",
    "A03: XSS via innerHTML": "An attacker who can inject content into this innerHTML assignment can execute arbitrary JavaScript in users' browsers, potentially stealing sessions or credentials.",
    "A07: Plaintext Password Comparison": "Passwords should never be compared in plaintext. An attacker with database access could read all user passwords. Use a proper password hashing library like bcrypt.",
    "A02: Weak Hash Function": "MD5 and SHA-1 are cryptographically broken. An attacker can generate collisions or reverse hashes. Use SHA-256 or bcrypt instead.",
    "A05: Wildcard CORS": "This CORS configuration allows any origin to make cross-origin requests. An attacker could create a malicious site that reads sensitive data from your API.",
    "MCP Server": finding.description || "Review this MCP server configuration for potential security issues.",
  };

  return scenarios[finding.label] || `This finding (${finding.label}) should be reviewed. ${finding.description || ""}`;
}

// ═══════════════════════════════════════════════════════════════════════════════
// Skill Definition
// ═══════════════════════════════════════════════════════════════════════════════

export default {
  name: "security_audit",
  description:
    "Comprehensive security audit. Scans the codebase for hardcoded secrets, " +
    "checks dependency vulnerabilities via npm audit, runs OWASP Top 10 analysis, " +
    "and reviews MCP server security configurations. " +
    "Generates a structured security report with exploit scenarios and fix recommendations. " +
    "Actions: scan (run full audit), quick (fast secret scan only), report (show last report).",

  parameters: {
    type: "object",
    properties: {
      action: {
        type: "string",
        enum: ["scan", "quick", "report"],
        description:
          "Action to perform:\n" +
          "- 'scan' → Run full security audit (secrets + dependencies + OWASP + MCP)\n" +
          "- 'quick' → Fast scan: secrets only (no npm audit, no OWASP)\n" +
          "- 'report' → Show the last security report",
      },
      path: {
        type: "string",
        description:
          "Project path to scan. Defaults to the current project root. " +
          "Example: /path/to/project",
      },
      confidenceThreshold: {
        type: "number",
        description:
          "Minimum confidence threshold (0.0 - 1.0). Findings below this threshold are filtered out. " +
          "Default: 0.7 (gstack's 8/10 confidence gate equivalent).",
      },
    },
    required: ["action"],
  },

  handler: async (params, options = {}) => {
    const { action, path: scanPath, confidenceThreshold } = params;

    // Store last report globally
    if (!global.__security_last_report) {
      global.__security_last_report = null;
    }

    switch (action) {
      case "scan":
      case "quick": {
        const rootDir = scanPath
          ? path.resolve(scanPath)
          : path.resolve(__dirname, "..");

        const isQuick = action === "quick";

        const result = await runSecurityScan(rootDir, {
          scanSecrets: true,
          scanDependencies: !isQuick,
          scanOWASP: !isQuick,
          scanMCP: !isQuick,
          confidenceThreshold: confidenceThreshold || 0.7,
        });

        // Generate report
        const report = generateReport(result);

        // Store for later retrieval
        global.__security_last_report = {
          summary: result.summary,
          report,
          timestamp: result.scannedAt,
        };

        return {
          success: true,
          summary: result.summary,
          report,
          isQuick,
          findingsCount: result.findings.length,
          message: isQuick
            ? `Quick security scan complete: ${result.summary.total} findings (${result.summary.bySeverity.HIGH} HIGH)`
            : `Full security audit complete: ${result.summary.total} findings (${result.summary.bySeverity.HIGH} HIGH, ${result.summary.bySeverity.MEDIUM} MEDIUM, ${result.summary.bySeverity.LOW} LOW)`,
        };
      }

      case "report": {
        if (!global.__security_last_report) {
          return {
            success: true,
            message: "No security audit has been run yet. Use action: 'scan' to run one.",
            report: null,
          };
        }
        return {
          success: true,
          ...global.__security_last_report,
        };
      }

      default:
        return { success: false, error: `Unknown action: "${action}"` };
    }
  },
};
