/**
 * lv-zero — Cloudflare Bridge (Phase 8: External Integrations)
 *
 * Code generation module for Cloudflare Workers.
 * Produces file content strings that can be written to disk.
 * No external dependencies needed.
 *
 * Modeled after Antigravity's cloudflare-expert skill.
 * All functions return { ok: bool, data/error }.
 * All wrapped in try/catch for graceful degradation.
 */

/**
 * Generate a Cloudflare Service Worker script content.
 * @param {object} [options] - Generation options
 * @param {string} [options.name] - Worker name (used in comments)
 * @param {string} [options.type] - Worker type: "fetch" (default), "scheduled", "queue", or "d1"
 * @param {string[]} [options.routes] - Route patterns to match
 * @param {boolean} [options.d1Binding] - Include D1 database binding boilerplate
 * @param {boolean} [options.r2Binding] - Include R2 bucket binding boilerplate
 * @param {boolean} [options.kvBinding] - Include KV namespace binding boilerplate
 * @param {boolean} [options.aiBinding] - Include AI binding boilerplate
 * @param {string} [options.customCode] - Custom JavaScript code to embed in the handler
 * @returns {{ ok: boolean, data?: string, error?: string }}
 */
function generateServiceWorker(options = {}) {
  try {
    const name = options.name || "my-worker";
    const type = options.type || "fetch";
    const routes = options.routes || [];
    const bindings = [];

    if (options.d1Binding) bindings.push("D1");
    if (options.r2Binding) bindings.push("R2");
    if (options.kvBinding) bindings.push("KV");
    if (options.aiBinding) bindings.push("AI");

    let content = `/**
 * ${name} — Cloudflare Worker
 * Generated by lv-zero Cloudflare Bridge
 * Type: ${type}
${routes.length ? ` * Routes: ${routes.join(", ")}` : ""}
${bindings.length ? ` * Bindings: ${bindings.join(", ")}` : ""}
 */

`;

    // Add binding accessor helpers
    if (options.d1Binding) {
      content += `// D1 Database binding
// const db = env.DB;\n\n`;
    }
    if (options.r2Binding) {
      content += `// R2 Bucket binding
// const bucket = env.MY_BUCKET;\n\n`;
    }
    if (options.kvBinding) {
      content += `// KV Namespace binding
// const kv = env.MY_KV;\n\n`;
    }
    if (options.aiBinding) {
      content += `// AI binding
// const ai = env.AI;\n\n`;
    }

    if (type === "fetch") {
      content += `export default {
  async fetch(request, env, ctx) {
    try {
      const url = new URL(request.url);
      const method = request.method;

      // CORS headers for cross-origin requests
      const corsHeaders = {
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Allow-Methods": "GET, POST, PUT, DELETE, OPTIONS",
        "Access-Control-Allow-Headers": "Content-Type, Authorization",
      };

      // Handle preflight CORS requests
      if (method === "OPTIONS") {
        return new Response(null, {
          headers: corsHeaders,
          status: 204,
        });
      }

${options.customCode ? `      // ── Custom handler code ──\n      ${options.customCode.replace(/\n/g, "\n      ")}\n` : `      // ── Default handler ──\n      return new Response(\`Hello from ${name}!\\n\`, {\n        headers: { "Content-Type": "text/plain", ...corsHeaders },\n      });`}

    } catch (err) {
      console.error(\`[${name}] Error: \${err.message}\`);
      return new Response(\`Internal Server Error: \${err.message}\`, {
        status: 500,
        headers: { "Content-Type": "text/plain" },
      });
    }
  },
};
`;
    } else if (type === "scheduled") {
      content += `export default {
  async scheduled(event, env, ctx) {
    try {
      console.log(\`[${name}] Triggered at \${new Date().toISOString()}\`);
${options.customCode ? `      ${options.customCode.replace(/\n/g, "\n      ")}` : `      // Add your scheduled task logic here`}
    } catch (err) {
      console.error(\`[${name}] Error: \${err.message}\`);
    }
  },
};
`;
    } else if (type === "queue") {
      content += `export default {
  async queue(batch, env, ctx) {
    try {
      for (const message of batch.messages) {
        console.log(\`[${name}] Processing message: \${message.id}\`);
${options.customCode ? `        ${options.customCode.replace(/\n/g, "\n        ")}` : `        // Process each message`}
        message.ack();
      }
    } catch (err) {
      console.error(\`[${name}] Error: \${err.message}\`);
    }
  },
};
`;
    } else if (type === "d1") {
      content += `export default {
  async fetch(request, env, ctx) {
    try {
      const url = new URL(request.url);
      const path = url.pathname;

      // D1 Database access
      const db = env.DB;

      if (path === "/query" && request.method === "POST") {
        const { sql, params } = await request.json();
        const result = await db.prepare(sql).bind(...(params || [])).all();
        return new Response(JSON.stringify({ success: true, result }), {
          headers: { "Content-Type": "application/json" },
        });
      }

      if (path === "/migrate" && request.method === "POST") {
        const { sql } = await request.json();
        await db.batch(sql.map((stmt) => db.prepare(stmt)));
        return new Response(JSON.stringify({ success: true, message: "Migration applied" }), {
          headers: { "Content-Type": "application/json" },
        });
      }

${options.customCode ? `      ${options.customCode.replace(/\n/g, "\n      ")}` : `      return new Response(\`${name} D1 Worker active\\n\`, {
        headers: { "Content-Type": "text/plain" },
      });`}

    } catch (err) {
      return new Response(\`Error: \${err.message}\`, { status: 500 });
    }
  },
};
`;
    }

    return { ok: true, data: content };
  } catch (err) {
    return { ok: false, error: `Failed to generate service worker: ${err.message}` };
  }
}

/**
 * Generate a wrangler.toml configuration file content.
 * @param {object} [options] - Configuration options
 * @param {string} [options.name] - Worker name
 * @param {string} [options.main] - Entry point file (default: "src/index.js")
 * @param {string} [options.compatibilityDate] - Compatibility date (default: current date)
 * @param {string[]} [options.routes] - Route patterns
 * @param {object[]} [options.d1Databases] - D1 database bindings [{ binding, databaseName, databaseId }]
 * @param {object[]} [options.r2Buckets] - R2 bucket bindings [{ binding, bucketName }]
 * @param {object[]} [options.kvNamespaces] - KV namespace bindings [{ binding, id }]
 * @param {object[]} [options.vars] - Environment variables [{ name, value }]
 * @param {object[]} [options.triggers] - Cron triggers for scheduled workers
 * @param {string[]} [options.queue] - Queue producers/consumers
 * @returns {{ ok: boolean, data?: string, error?: string }}
 */
function generateWranglerConfig(options = {}) {
  try {
    const name = options.name || "my-worker";
    const main = options.main || "src/index.js";
    const compatDate = options.compatibilityDate || new Date().toISOString().slice(0, 10);

    let toml = `# Wrangler configuration for ${name}
# Generated by lv-zero Cloudflare Bridge
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/

name = "${name}"
main = "${main}"
compatibility_date = "${compatDate}"
\n`;

    // Routes
    if (options.routes && options.routes.length > 0) {
      toml += "routes = [\n";
      for (const route of options.routes) {
        toml += `  { pattern = "${route}", zone_id = "" },\n`;
      }
      toml += "]\n\n";
    }

    // D1 databases
    if (options.d1Databases && options.d1Databases.length > 0) {
      toml += "[[d1_databases]]\n";
      for (const db of options.d1Databases) {
        toml += `binding = "${db.binding}"\n`;
        toml += `database_name = "${db.databaseName}"\n`;
        toml += `database_id = "${db.databaseId || ""}"\n\n`;
      }
    }

    // R2 buckets
    if (options.r2Buckets && options.r2Buckets.length > 0) {
      toml += "[[r2_buckets]]\n";
      for (const bucket of options.r2Buckets) {
        toml += `binding = "${bucket.binding}"\n`;
        toml += `bucket_name = "${bucket.bucketName}"\n\n`;
      }
    }

    // KV namespaces
    if (options.kvNamespaces && options.kvNamespaces.length > 0) {
      toml += "[[kv_namespaces]]\n";
      for (const kv of options.kvNamespaces) {
        toml += `binding = "${kv.binding}"\n`;
        toml += `id = "${kv.id}"\n\n`;
      }
    }

    // Environment variables
    if (options.vars && options.vars.length > 0) {
      toml += "[vars]\n";
      for (const v of options.vars) {
        toml += `${v.name} = "${v.value}"\n`;
      }
      toml += "\n";
    }

    // Cron triggers
    if (options.triggers && options.triggers.length > 0) {
      toml += "[triggers]\n";
      toml += 'crons = ["' + options.triggers.join('", "') + '"]\n\n';
    }

    // Queue consumers
    if (options.queue && options.queue.length > 0) {
      toml += "[[queues]]\n";
      toml += `producers = ["${options.queue.join('", "')}"]\n\n`;
    }

    return { ok: true, data: toml };
  } catch (err) {
    return { ok: false, error: `Failed to generate wrangler config: ${err.message}` };
  }
}

/**
 * Generate a deployment guide for a Cloudflare Workers project.
 * @param {string} projectPath - Path to the project directory
 * @returns {{ ok: boolean, data?: string, error?: string }}
 */
function generateDeployGuide(projectPath) {
  try {
    const path = require("path");
    const projectName = projectPath ? path.basename(projectPath) : "my-worker";

    const guide = `# Deploy Guide: ${projectName}

## Prerequisites

1. Install [Node.js](https://nodejs.org/) (v18 or later)
2. Install Wrangler CLI:
   \`\`\`bash
   npm install -g wrangler
   \`\`\`
3. Authenticate with Cloudflare:
   \`\`\`bash
   wrangler login
   \`\`\`

## Project Structure

\`\`\`
${projectPath}/
├── src/
│   └── index.js      # Worker entry point
├── wrangler.toml      # Wrangler configuration
├── package.json        # Node dependencies
└── node_modules/       # (generated by npm install)
\`\`\`

## Configuration

Edit \`wrangler.toml\` to set:
- \`name\`: Your worker name
- \`compatibility_date\`: Date for API compatibility
- Routes, bindings (D1, R2, KV, AI) as needed

## Development

Run the local development server:
\`\`\`bash
wrangler dev
\`\`\`

## Deploy

Deploy to Cloudflare's global network:
\`\`\`bash
wrangler deploy
\`\`\`

## Common Wrangler Commands

| Command | Description |
|---------|-------------|
| \`wrangler dev\` | Start local development server |
| \`wrangler deploy\` | Deploy worker to Cloudflare |
| \`wrangler tail\` | Stream logs from deployed worker |
| \`wrangler secret put <NAME>\` | Set a secret environment variable |
| \`wrangler kv:key put\` | Write a KV key-value pair |
| \`wrangler d1 execute\` | Execute SQL on D1 database |
| \`wrangler r2 object\` | Manage R2 objects |
| \`wrangler login\` | Authenticate Wrangler CLI |
| \`wrangler whoami\` | Show current authentication |
| \`wrangler init\` | Scaffold a new worker project |

## Environment Variables

Sensitive values should be set as secrets:
\`\`\`bash
wrangler secret put API_KEY
\`\`\`

Non-sensitive values go in \`wrangler.toml\` under \`[vars]\`.
`;

    return { ok: true, data: guide };
  } catch (err) {
    return { ok: false, error: `Failed to generate deploy guide: ${err.message}` };
  }
}

/**
 * List common Wrangler CLI commands as a reference array.
 * @returns {{ ok: boolean, data?: Array<{command: string, description: string}>, error?: string }}
 */
function listWranglerCommands() {
  try {
    const commands = [
      { command: "wrangler init [name]", description: "Scaffold a new Cloudflare Workers project" },
      { command: "wrangler dev", description: "Start local development server with hot reload" },
      { command: "wrangler deploy", description: "Deploy worker to Cloudflare's global network" },
      { command: "wrangler tail", description: "Stream live logs from a deployed worker" },
      { command: "wrangler login", description: "Authenticate Wrangler with your Cloudflare account" },
      { command: "wrangler logout", description: "Log out of Cloudflare account" },
      { command: "wrangler whoami", description: "Display current user and account info" },
      { command: "wrangler secret put <key>", description: "Create or update a secret environment variable" },
      { command: "wrangler secret list", description: "List all secret names for a worker" },
      { command: "wrangler secret delete <key>", description: "Delete a secret" },
      { command: "wrangler kv:key put <key>=<value>", description: "Write a key-value pair to KV namespace" },
      { command: "wrangler kv:key get <key>", description: "Read a value from KV namespace" },
      { command: "wrangler kv:key delete <key>", description: "Delete a key from KV namespace" },
      { command: "wrangler kv:namespace create", description: "Create a new KV namespace" },
      { command: "wrangler d1 list", description: "List all D1 databases" },
      { command: "wrangler d1 create <name>", description: "Create a new D1 database" },
      { command: "wrangler d1 execute <database> --command=<sql>", description: "Execute SQL on a D1 database" },
      { command: "wrangler d1 migrations create <database> <name>", description: "Create a new D1 migration" },
      { command: "wrangler d1 migrations apply <database>", description: "Apply pending D1 migrations" },
      { command: "wrangler r2 bucket create <name>", description: "Create a new R2 bucket" },
      { command: "wrangler r2 bucket list", description: "List all R2 buckets" },
      { command: "wrangler types", description: "Generate TypeScript types for worker bindings" },
      { command: "wrangler version", description: "Show Wrangler version" },
    ];
    return { ok: true, data: commands };
  } catch (err) {
    return { ok: false, error: `Failed to list wrangler commands: ${err.message}` };
  }
}

module.exports = {
  generateServiceWorker,
  generateWranglerConfig,
  generateDeployGuide,
  listWranglerCommands,
};
